name: CI/CD Pipeline for Docker and EC2

on:
  push:
    branches:
      - main  # main 브랜치에 커밋이 있을 때마다 실행

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub Actions는 기본적으로 Ubuntu에서 실행됩니다.
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 리포지토리의 코드를 체크아웃

      - name: Set up SSH for EC2
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}  # EC2의 비공개 SSH 키를 GitHub Secrets에 저장하고 사용

      - name: SSH into EC2 and update Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            echo "Stopping Docker Compose services..."
            cd ~/NaeZuO  # Docker Compose 파일이 있는 디렉토리로 이동
            sudo docker compose down  # 기존 컨테이너 중지
            echo "Pulling latest code from GitHub..."
            git pull origin main  # 최신 커밋을 반영
            echo "Starting gradlew build..."
            ./gradlew build -x test
            sudo docker compose down -v
            echo "Starting Docker Compose services..."
            sudo docker compose up -d --build  # Docker Compose 컨테이너 재시작
          EOF
